# Generated by Django 4.1.9 on 2023-06-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_floorplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='measurement_unit',
            field=models.CharField(default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='scale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
