# Generated by Django 4.1.9 on 2023-07-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_floorplan', '0006_delete_floorplanobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorplan',
            options={'ordering': ('site', 'location', 'background_image', 'width', 'height', 'measurement_unit')},
        ),
        migrations.RenameField(
            model_name='floorplan',
            old_name='scale',
            new_name='height',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
